name: java-project
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: cloning the github
        uses: actions/checkout@v7.0.0

      - name: setup java
        uses: actions/setup-java@v5.5.0
        with:
           java-version: '21'
           distribution: 'temurin'

      - name: compile java
        run: javac Test.java

      - name: run java
        run: java Test

        
